# Generated by Django 5.1.2 on 2024-12-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='replies',
            field=models.ManyToManyField(blank=True, related_name='review_replies', to='product.reviewrating'),
        ),
    ]
