# Generated by Django 5.1.2 on 2024-12-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_reviewrating_replies_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_holiday_promotion',
            field=models.BooleanField(default=False),
        ),
    ]
