# Generated by Django 5.1.2 on 2024-12-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_expiry_date_product_is_holiday_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='holiday_promotion_type',
            field=models.CharField(blank=True, choices=[('buy2get1', 'Mua 2 tặng 1'), ('discount10', 'Giảm 10%')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='holidays',
            field=models.ManyToManyField(blank=True, to='product.holiday'),
        ),
    ]
