# Generated by Django 5.1.4 on 2025-01-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=250, unique=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('order_id', models.IntegerField()),
            ],
        ),
    ]
